version: "3"
services:
  postgresql:
    image: "postgres:13.10-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backend-assessment
    ports:
      - 5432:5432
